openapi: 3.1.0
info:
  title: Comuting API
  description: |-
    This is the first draft of commuting API.
    以下除了 /login 外均需要在登入狀態下才能呼叫，若未登入會產生 401 錯誤。所有傳入錯誤參數的 request ，均會得到 400 錯誤。
  version: 1.0.0
servers:
  - url: https://www.cloudnative23.com/api
tags:
  - name: user
    description: 跟使用者相關操作
  - name: driver
    description: 跟司機相關操作
  - name: passenger
    description: 跟乘客相關操作
paths:
  /login:
    $ref: paths/login.yaml
  /logout:
    $ref: paths/logout.yaml
  /me:
    $ref: paths/me.yaml
  /routes:
    $ref: paths/routes.yaml
  /routes/{id}:
    $ref: paths/routes/{id}.yaml
  /routes/{id}/stations:
    $ref: paths/routes/{id}/stations.yaml
  /routes/{id}/stations/{station_id}:
    $ref: paths/routes/{id}/stations/{station_id}.yaml
  /requests:
    $ref: paths/requests.yaml
  /requests/{id}:
    $ref: paths/requests/{id}.yaml
  /requests/{id}/accept:
    $ref: paths/requests/{id}/accept.yaml
  /requests/{id}/deny:
    $ref: paths/requests/{id}/deny.yaml
  /notifications:
    $ref: paths/notifications.yaml
  /notifications/read:
    $ref: paths/notifications/read.yaml
  /notifications/{id}:
    $ref: paths/notifications/{id}.yaml
  /notifications/{id}/read:
    $ref: paths/notifications/{id}/read.yaml
  /stations:
    $ref: paths/stations.yaml
  /stations/{id}:
    $ref: paths/stations/{id}.yaml
components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      name: SESSION_ID
      in: cookie
